apiVersion: v1
kind: Template
metadata:
  name: msg-processor-app-template
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: msg-processor
    name: app-secrets
  data:
    mq-user: dXNlcg==
    mq-pwd: cGFzczEyMw==
    db-user: ZGJ1c2Vy
    db-pwd: ZGJwYXNzMTIz
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: msg-processor
    name: msg-processor
  spec:
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/jc-wkshp/msg-processor
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.2
          namespace: openshift
      type: Source
    output:
      to:
        kind: ImageStreamTag
        name: msg-processor:latest
    triggers:
    - type: GitHub
      github:
        secret: jc-wkshp-msg-app
    - type: ConfigChange
    - type: ImageChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: msg-processor
    name: msg-processor
  spec:
    replicas: 1
    selector:
      app: msg-processor
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: msg-processor
        name: msg-processor
      spec:
        containers:
        - env:
          - name: MQ_USER
            valueFrom:
              secretKeyRef:
                name: app-secrets                
                key: mq-user
          - name: MQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets                
                key: mq-pwd 
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: app-secrets                
                key: db-user 
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets                
                key: db-pwd                                           
          image: msg-processor:latest
          imagePullPolicy: Always
          name: msg-processor
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              cpu: 100m 
              memory: 500Mi 
            limits:
              cpu: 1000m 
              memory: 1Gi 
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - msg-processor
        from:
          kind: ImageStreamTag
          name: msg-processor:latest
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: msg-processor
    name: msg-processor
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: msg-processor
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: msg-processor
    name: msg-processor
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: msg-processor  
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: msg-processor
    name: msg-processor
  spec:
    lookupPolicy:
      local: false